### ISSUE TITLE
Ability to specify API key from WP Admin options page

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/transit-base-template#4]
Rather than requiring modifying the template code to add Google Places autocomplete to the trip planner, add a theme options page that includes an option for Google API key.

After, update functions.php to load the script if key is supplied, and alter planner.js to determine if the script is active.

**Comment by sleddd** [comment]
Instead of adding an settings page which is really more for plugins or extensive options - I added a section and field to the  theme customizer.  See screenshots below. If you approve, then I will merge this over into the master branch.
<img width="286" alt="Screen Shot 2020-06-25 at 12 01 47 PM" src="https://user-images.githubusercontent.com/1176945/85783126-e5ef9c00-b6db-11ea-87a9-5b19fc43bea1.png">

**Comment by sleddd** [comment]
Since this is a theme option versus a setting, I added a section and field to the theme customizer. See screenshots below. If you approve, then I will merge this over to the master branch.
<img width="295" alt="Screen Shot 2020-06-25 at 12 01 29 PM" src="https://user-images.githubusercontent.com/1176945/85783259-00297a00-b6dc-11ea-8aff-0daeb4edda44.png">
<img width="286" alt="Screen Shot 2020-06-25 at 12 01 47 PM" src="https://user-images.githubusercontent.com/1176945/85783255-ff90e380-b6db-11ea-92dc-54d5e85e03e7.png">

**Comment by NomeQ** [comment]
Do anything you like with this theme that makes sense to you,
development-wise. It's only purpose is to make development (and
maintenance) easier, by ensuring themes are somewhat similar. It's a
project I started on the side and never made it very far with, and any
issues in the GitHub are really just notes to self about ideas I've had.

**Comment by sleddd** [comment]
Thanks Nome! Will do then.
